[versions]
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2025.10.01"
compose-version = "1.7.8"
navigation = "2.9.5"
timber = "5.0.1"
okhttp-bom = "5.2.1"
koin-bom = "4.1.1"
retrofit = "3.0.0"
converter-kotlinx-serialization = "3.0.0"
animationCore = "1.9.4"
material3-version = "1.4.0"
kotlinx-serialization-json = "1.7.3"
coil-version = "3.0.0-alpha06"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-version" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3-version" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-animation-core = { group = "androidx.compose.animation", name = "animation-core", version.ref = "animationCore" }
androidx-navigation-compose-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation" }
com-jakewharton-timber-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
com-squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
com-squareup-okhttp3-okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp-bom" }
com-squareup-retrofit2-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "converter-kotlinx-serialization" }
org-jetbrains-kotlinx-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
com-squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
io-insert-koin-koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin-bom" }
io-insert-koin-koin-core = { group = "io.insert-koin", name = "koin-core" }
io-insert-koin-koin-android-test = { group = "io.insert-koin", name = "koin-android-test" }
io-insert-koin-koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
io-insert-koin-koin-androidx-startup = { group = "io.insert-koin", name = "koin-androidx-startup" }
io-insert-koin-koin-android = { group = "io.insert-koin", name = "koin-android" }
io-insert-koin-koin-test-junit4 = { group = "io.insert-koin", name = "koin-test-junit4" }
io-coil-kt-coil3-coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-version" }
io-coil-kt-coil3-coil-network = { group = "io.coil-kt.coil3", name = "coil-network", version.ref = "coil-version" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

